#Obtenção de Variáveis do Censo para o cálculo do Índice de Vulnerabilidade Social Costeiro
#Aplicação nos municípios costeiros do Brasil
#Menor unidade de análise: setor censitário

rm(list=ls()) ## Removendo as variáveis

#Loading and installing packages------------


# Install github packages
# install.packages("devtools")
# library("devtools")
# install_github("kassambara/factoextra")

# library(devtools)
# install_github("vqv/ggbiplot")

# Conferindo instalação de pacotes uma a um
# library (ggplot2)
# install.packages ("ggplot2")


  
packages<-c('ggplot2','dplyr','corrplot','factoextra','reshape','smacof','gdata', 'ggbiplot')

package.check <- lapply(packages, FUN = function(x) {
  if (!require(x, character.only = TRUE)) {
    install.packages(x, dependencies = TRUE)
    library(x, character.only = TRUE)
  }
})


rm(list=ls()) ## Cleaning workspace

#Setting ggplot defaults---------
theme_set(
  theme_bw(base_size = 10)+
    theme(text=element_text(family="Times"))
)

##Loading data---------------
#Generated by the script 00_gattering_IBGEcensus
load('input_data/descritores_IVSCostV2.RData')

rm(setores_sf)

#V5: Selecting variables--------------
set<-setores%>%transmute(cod_setor=cod_setor,
                         cod_mun=cod_mun,
                         nome_mun=nome,
                         cod_state=substring(as.character(cod_setor),1,2),
                         cod_regiao=substring(as.character(cod_setor),1,1),
                         cd01=mordom,
                         cd02=1-(domalug/poptotal),
                         # cd03=renda/poptotal,
                         # cd04=abaixopob/ndom,
                         # cd05=srenda/ndom,
                         # cp01=mulheres/poptotal,
                         cp01=rendavul/poptotal,
                         cp02=(criancas+idosos)/poptotal,
                         cp03=raca/poptotal,
                         cp04=(pmais5-alfabet)/poptotal,
                         ci01=(poptotal-cagua)/poptotal,
                         ci02=(poptotal-cbanhesg)/poptotal,
                         ci03=(poptotal-ccoletalixo)/poptotal,
                         ci04=sempav/poptotal
)


set<-set%>%mutate(regiao=case_when(cod_regiao==1 ~ 'N',
                                   cod_regiao==2 ~ 'NE',
                                   cod_regiao==3 ~ 'SE',
                                   cod_regiao==4 ~ 'S')) 
set<-set%>%mutate(cd01=(cd01-min(cd01))/(max(cd01)-min(cd01)))



#Checking data--------------
summary(set)
#Removing percents greater than 1
set<-set%>%filter(cd02<=1,cp02<=1,cp03<=1, ci01<=1,
                       ci02<=1,ci03<=1)
#Keeping complete cases
set<-set[complete.cases(set),] 

#Removing some variables
seti<-set%>%select(-cod_mun, -cod_state, -nome_mun,  -cod_regiao, -regiao)


#Histogram---------------
set.m<-melt(seti,id='cod_setor')
ggplot(set.m,aes(x=value))+geom_histogram()+
  facet_wrap(~variable,scales='free',ncol = 3)+
  theme_bw()+xlab(NULL)+ylab(NULL)
ggsave('figures/histogramas_v5.jpg',dpi=200, units='cm', width=15, height=14)

#Correlogram-------------------

seti<-seti%>%select(-regiao)

M<-cor(seti,method='pearson')

jpeg('figures/correlograma_varbrutas_v5.jpg',width=15,height = 15,units='cm',res=300)
corrplot(M,type='upper',method = 'number')
dev.off()

#Correlogram for all initial variables
setall<-setores%>%transmute(nb_houses=ndom,
                         total_pop=poptotal,
                         pop_house=mordom,
                         rent_house=domalug/ndom,
                         pop_income=renda,
                         pop_female=mulheres/poptotal,
                         pop_poverty=rendavul/poptotal,
                         pop_agevul=(criancas+idosos)/poptotal,
                         pop_nonwhite=raca/poptotal,
                         pop_iliterate=(pmais5-alfabet)/poptotal,
                         pop_nowater=(poptotal-cagua)/poptotal,
                         pop_nosewage=(poptotal-cbanhesg)/poptotal,
                         pop_nogarbage=(poptotal-ccoletalixo)/poptotal,
                         pop_nopaving=sempav/poptotal,
                         pop_noeletricity=(poptotal-cenergia)/poptotal
)
setall<-setall[complete.cases(setall),]

M<-cor(setall,method='pearson')

jpeg('figures/correlograma_varall_v1.jpg',width=15,height = 15,units='cm',res=300)
corrplot(M,type='upper',method = 'pie')
dev.off()

#PCA: General-----------
pc<-prcomp(seti[-1],scale = TRUE)

summary(pc)

#Getting PCA Info
pca<-get_pca(pc, element = c("var", "ind"))
pc_contrib<-as.data.frame(pca$contrib)
pc_cor<-as.data.frame(pca$cor)
pcgeral<-as.data.frame(pc$x)

#Screeplot
fviz_screeplot(pc, choice='eigenvalue', geom='line')+
  ylab('Variância')+xlab('PCs')+ggtitle(NULL)+
  geom_hline(yintercept=1, linetype='dashed')
ggsave('figures/pca_screeV5.jpg', width=15, heigh=8, units='cm',dpi=150)

#Roda PCA
fviz_pca_var(pc,axes = c(1,2),
             col.var = "contrib", # Color by contributions to the PC
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE,     # Avoid text overlapping
             title='')+
  theme(text=element_text(family='Times',size=10),
        legend.position = 'none')
ggsave("figures/pca_wheelV5.jpg", dpi=500, units='cm', width=14, height=14)

#Biplot
install.packages('ggokabeito')
require(ggokabeito)
ggbiplot(pc, choices=c(1,2), obs.scale = 1, var.scale = 1,
         groups = set$regiao,ellipse = T,varname.size = 4,
         varname.adjust = 2, alpha=.01) +
  scale_color_okabe_ito(order=c(7,4,6,5),name='')+
  # scale_color_brewer(palette.colors(palette='Okabe-Ito'), name='') +
  ylim(c(-6,6))+
  xlim(c(-7,7))+
  # theme(legend.direction = 'horizontal', legend.position = 'top')+
  theme_bw()

ggsave("figures/pca_biplot_v6.jpg",dpi=300, units = 'cm', width = 15, height = 14)

#PCA Regression------------
library(pls)
install.packages('formula.tools')
library(formula.tools)

pcr_model <- pcr(ci04~., data = d, scale = TRUE, validation = "CV")
summary(pcr_model)
# Plot the R2
jpeg('figures/pcr_ci04.jpg',width=15,height = 10,units='cm',res=300)
validationplot(pcr_model, val.type = "R2")
dev.off()



#Merge PCAs - setores-------------
pc_ci<-pcinfra%>%transmute(ci_pc1=PC1,
                             ci_pc2=PC2,
                             ci_pc3=PC3)
pc_cp<-pcpessoais%>%transmute(cp_pc1=PC1,
                           cp_pc2=PC2,
                           cp_pc3=PC3)
pc_g<-pcgeral%>%transmute(all_pc1=PC1,
                              all_pc2=PC2,
                              all_pc3=PC3)

seti<-cbind(seti,pc_cp,pc_ci,pc_g)

#IVS: 1st option-----------------------

seti<-seti%>%mutate(ivs1=all_pc1)#PC1 de todas as variáveis em conjunto

#R2 para IVS1----------
summary(lm(cd01 ~ ivs1, data=seti))
summary(lm(cd02 ~ ivs1, data=seti))
summary(lm(cp01 ~ ivs1, data=seti))
summary(lm(cp02 ~ ivs1, data=seti))
summary(lm(cp03 ~ ivs1, data=seti))
summary(lm(cp04 ~ ivs1, data=seti))
summary(lm(ci01 ~ ivs1, data=seti))
summary(lm(ci02 ~ ivs1, data=seti))
summary(lm(ci03 ~ ivs1, data=seti))
summary(lm(ci04 ~ ivs1, data=seti))


#IVS: 2nd option-----------------------
seti<-seti%>%mutate(ivs2=(cp_pc1+ci_pc1)/2)#Média da somas da PC1cpd e PC1ci

#R2 para IVS2----------
summary(lm(cd01 ~ ivs2, data=seti))
summary(lm(cd02 ~ ivs2, data=seti))
summary(lm(cp01 ~ ivs2, data=seti))
summary(lm(cp02 ~ ivs2, data=seti))
summary(lm(cp03 ~ ivs2, data=seti))
summary(lm(cp04 ~ ivs2, data=seti))
summary(lm(ci01 ~ ivs2, data=seti))
summary(lm(ci02 ~ ivs2, data=seti))
summary(lm(ci03 ~ ivs2, data=seti))
summary(lm(ci04 ~ ivs2, data=seti))

#Saving Rda-------------
head(setores)#variáveis brutas
head(seti)#PCA e IVS

setores<-merge(setores,seti,by=c('cod_setor'),all.x=T)

save(setores,file='output_data/setores_ivs.Rda')


#Rescaling IVS for values between 0 and 1-------------
load('output_data/setores_ivs.Rda')



x<-setores$ivs1
setores$ivsf<- (x-min(x,na.rm=T))/(max(x, na.rm = T)-min(x, na.rm=T))*100

ggplot(setores, aes(x=ivs1))+geom_histogram()
ggplot(setores, aes(x=ivsf))+geom_histogram()

write.csv2(setores,"output_data/setores_ivs.csv")
save(setores,file='output_data/setores_ivs.Rda')
